### ISSUE TITLE
Toast消失问题

### ISSUE THREAD

**Issue by hrimyx** [devSC/WSProgressHUD#13]
如果点击出现了一个透明指示层，在它即将消失的时候，同一页面点击其他可以触发透明指示层的按钮，新出现的Toast刚刚出现就会和即将消失的Toast一起消失掉

**Comment by devSC** [comment]
你是怎么去处理Toast消失的?

最好能贴一下代码哈.

**Comment by hrimyx** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15710954/24131406/85a6adba-0e29-11e7-9c4b-2cc297df97bc.gif)
都是[WSProgressHUD showImage:nil status:@"showString-短"];这样
最开始两次是正常点击，第三次先短后长，你应该能看到长的没出现，实际上是刚出现就和短的一起消失了。后面几次都是先长后短，最次一次闪的那一下你应该能看到。

**Comment by devSC** [comment]
嗯, 看到了, 感谢反馈.

**Comment by devSC** [comment]
@bv5204978 问题已在1.1.2版本中修复. 请更新一下库版本.

如有发现其他问题, 欢迎提PR和issue. 😄
