### ISSUE TITLE
请问1.1.4版本什么时候可以pod下来? 1.1.3不支持iphoneX

### ISSUE THREAD

**Issue by wangchao2010** [devSC/WSProgressHUD#26]

**Comment by devSC** [comment]
`1.1.4` 昨天已经上线了.

如果本地搜不到，先运行：`pod setup` 更新本地 repo 索引后再尝试更新。

**Comment by wangchao2010** [comment]
好的我试试

**Comment by wangchao2010** [comment]
1.1.4pod下来之后和master的不一样,没有支持ios13

 通过pod 'WSProgressHUD', :git => 'https://github.com/devSC/WSProgressHUD.git', :branch => 'master'可以

**Comment by devSC** [comment]
稍后我查看一下问题。

**Comment by devSC** [comment]
可以升级至：`1.1.5` 版本
