### ISSUE TITLE
您好，在 Podfile 加入 :generate_multiple_pod_projects => true 之后，编译不能通过

### ISSUE THREAD

**Issue by angelen10** [devSC/WSProgressHUD#28]
我在 Podfile 中加入以下代码：
```
install! 'cocoapods',
  :deterministic_uuids => false,
  :disable_input_output_paths => true,
  :generate_multiple_pod_projects => true
```

在编译的时候报错：`'FBShimmeringView.h' file not found`
截图如下：
<img width="759" alt="image" src="https://user-images.githubusercontent.com/4332610/80356221-b96dfe00-88ab-11ea-8306-f7dd5c1eb0b8.png">

WSProgressHUD 版本为 1.1.5

**Comment by devSC** [comment]
好的，感谢反馈
