### ISSUE TITLE
WSProgressHUDMaskTypeClear

### ISSUE THREAD

**Issue by mf168** [devSC/WSProgressHUD#4]
case WSProgressHUDMaskTypeClear: {
            CGContextRef context = UIGraphicsGetCurrentContext();
            [[UIColor colorWithWhite:0 alpha:0.5] set];
            CGRect bounds = self.bounds;
            CGContextFillRect(context, bounds);
aplha 应该为0

**Comment by devSC** [comment]
你好,请pod update升级一下, 这个问题在1.0.7中就修复了.

**Comment by mf168** [comment]
好的 thk
