### ISSUE TITLE
首次使用showSuccessWithStatus方法时没有图片！

### ISSUE THREAD

**Issue by jming0618** [devSC/WSProgressHUD#5]

**Comment by devSC** [comment]
你好,具体使用场景是什么? 或者,方便看看您使用部分的代码嘛?

**Comment by jming0618** [comment]
[WSProgressHUD showSuccessWithStatus:@"第一次调用,打钩的图片不显示"];

**Comment by devSC** [comment]
问题已经修复. 请更新下库版本.(Cocoapods 或者本地文件)
